// The starter restricted days: parsed from supabase/seed/calendar.psv, the one
// hand-edited source, read from published Tamil calendars (never calculated). `npm run
// catalog` turns it into migration 0010 and the review table docs/CALENDAR.md. Runs in
// Node too (scripts/build-catalog.ts), so it uses no browser or app imports.

import { CALENDAR_TYPES, TYPE_NAMES, type CalendarType } from './types.ts'

export interface CatalogDay {
  date: string
  end_date: string | null
  type: CalendarType
  label: string
  /** Which published calendars list this date. */
  sources: string[]
  /** Anything to check (sources disagreeing, only one source). */
  note: string
}

export const CALENDAR_COLUMNS = ['date', 'end_date', 'type', 'label', 'sources', 'note'] as const

const DATE = /^\d{4}-\d{2}-\d{2}$/
const isRealDate = (s: string) => DATE.test(s) && new Date(`${s}T00:00:00Z`).toISOString().startsWith(s)

/** One entry per line, columns separated by "|". Throws with the line number on anything invalid. */
export function parseCalendarCatalog(text: string): CatalogDay[] {
  const out: CatalogDay[] = []
  let header = true
  text.split(/\r?\n/).forEach((raw, i) => {
    const line = raw.trim()
    if (!line || line.startsWith('#')) return
    const cells = line.split('|').map((c) => c.trim())
    const where = `calendar.psv line ${i + 1}`
    if (header) {
      if (cells.join('|') !== CALENDAR_COLUMNS.join('|')) throw new Error(`${where}: header should be ${CALENDAR_COLUMNS.join(' | ')}`)
      header = false
      return
    }
    if (cells.length !== CALENDAR_COLUMNS.length) throw new Error(`${where}: expected ${CALENDAR_COLUMNS.length} columns, got ${cells.length}`)
    const [date, end, type, label, sources, note] = cells
    if (!isRealDate(date)) throw new Error(`${where}: "${date}" isn't a date like 2026-10-10`)
    if (!CALENDAR_TYPES.includes(type as CalendarType) || type === 'family_custom') throw new Error(`${where}: unknown type "${type}"`)
    if (end && !isRealDate(end)) throw new Error(`${where}: end date "${end}" isn't a date`)
    if (end && type !== 'puratasi') throw new Error(`${where}: only Puratasi has an end date`)
    if (type === 'puratasi' && !end) throw new Error(`${where}: Puratasi needs an end date`)
    if (end && end < date) throw new Error(`${where}: ends before it starts`)
    const sourceList = sources
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
    if (!sourceList.length) throw new Error(`${where}: every date needs at least one source`)
    out.push({ date, end_date: end || null, type: type as CalendarType, label, sources: sourceList, note })
  })
  const seen = new Set<string>()
  for (const d of out) {
    const key = `${d.date}:${d.type}`
    if (seen.has(key)) throw new Error(`calendar.psv: ${d.type} on ${d.date} is listed twice`)
    seen.add(key)
  }
  return out
}

/** The note kept with each date in the app: its sources, and anything to check. */
export const dayNote = (d: CatalogDay) => `Sources: ${d.sources.join(', ')}.${d.note ? ` ${d.note[0].toUpperCase()}${d.note.slice(1)}.` : ''}`

const sqlText = (s: string) => `'${s.replace(/'/g, "''")}'`

/** Migration 0010: load the dates and give every existing household its copy. */
export function calendarToSql(days: readonly CatalogDay[]): string {
  const rows = days.map(
    (d) => `  (${[sqlText(d.date), d.end_date ? sqlText(d.end_date) : 'null', sqlText(d.type), sqlText(d.label), sqlText(dayNote(d))].join(', ')})`,
  )
  return `-- ============================================================================
-- PRABAS Food Planner · 0010 starter restricted days (2026 and 2027)
--
-- GENERATED by \`npm run catalog\` from supabase/seed/calendar.psv.
-- Edit that file, not this one. (${days.length} entries.)
--
-- Read from published Tamil calendars for Chennai; none calculated or guessed. They
-- arrive unverified, to be checked against a trusted panchangam in the app.
-- Safe to run again: dates a household already has (or has confirmed) are left alone.
-- ============================================================================

insert into private.calendar_catalog (date, end_date, type, label, note) values
${rows.join(',\n')}
on conflict (date, type) do update set
  end_date = excluded.end_date, label = excluded.label, note = excluded.note;

select private.seed_household_calendar(id) from public.households;
`
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const pretty = (s: string) => {
  const d = new Date(`${s}T00:00:00Z`)
  return `${WEEKDAYS[d.getUTCDay()]} ${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`
}

/** The review table: every date with its sources, ones to look at closely marked. */
export function calendarToMarkdown(days: readonly CatalogDay[]): string {
  const years = [...new Set(days.map((d) => d.date.slice(0, 4)))].sort()
  const flagged = days.filter((d) => d.note).length
  const sections = years.flatMap((y) =>
    (['amavasai', 'kiruthigai', 'puratasi'] as const).map((t) => {
      const rows = days.filter((d) => d.type === t && d.date.startsWith(y))
      if (!rows.length) return ''
      return [
        `## ${TYPE_NAMES[t]} ${y} (${rows.length})`,
        '',
        '| Date | Sources | Check |',
        '|---|---|---|',
        ...rows.map((d) => `| ${pretty(d.date)}${d.end_date ? ` – ${pretty(d.end_date)}` : ''}${d.label ? ` (${d.label})` : ''} | ${d.sources.join(', ')} | ${d.note ? `**${d.note}**` : ''} |`),
        '',
      ].join('\n')
    }),
  )
  return `# Restricted days for 2026 and 2027 (${days.length} entries)

Generated by \`npm run catalog\` from \`supabase/seed/calendar.psv\`.

**Please check these against your panchangam.** They were read from published Tamil
calendars for Chennai (drikpanchang, tamildailycalendar, goldenchennai, tamildot,
prokerala); none were calculated or guessed. Every date arrives unverified, and
unverified days still mean no non-veg.

${flagged} entries are marked in **bold**: the sources disagreed (both days are listed, so
both stay veg-only until you confirm the right one and remove the other), or only one source
was found. Confirm or fix them in the app under Settings → Calendar, or tell me the fixes.

Saturdays aren't listed: every Saturday is veg-only by rule.

${sections.filter(Boolean).join('\n')}`
}
