-- ============================================================================
-- PRABAS Food Planner · 0010 starter restricted days (2026 and 2027)
--
-- GENERATED by `npm run catalog` from supabase/seed/calendar.psv.
-- Edit that file, not this one. (64 entries.)
--
-- Read from published Tamil calendars for Chennai; none calculated or guessed. They
-- arrive unverified, to be checked against a trusted panchangam in the app.
-- Safe to run again: dates a household already has (or has confirmed) are left alone.
-- ============================================================================

insert into private.calendar_catalog (date, end_date, type, label, note) values
  ('2026-01-18', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar, goldenchennai.'),
  ('2026-02-17', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar, goldenchennai.'),
  ('2026-03-18', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar. Goldenchennai says 19 Mar.'),
  ('2026-03-19', null, 'amavasai', '', 'Sources: goldenchennai. Drikpanchang and tamildailycalendar say 18 Mar.'),
  ('2026-04-17', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar, goldenchennai.'),
  ('2026-05-16', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar, goldenchennai.'),
  ('2026-06-14', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar. Goldenchennai says 15 Jun.'),
  ('2026-06-15', null, 'amavasai', '', 'Sources: goldenchennai. Drikpanchang and tamildailycalendar say 14 Jun.'),
  ('2026-07-14', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar, goldenchennai.'),
  ('2026-08-12', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar, goldenchennai.'),
  ('2026-09-10', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar. Goldenchennai says 11 Sep.'),
  ('2026-09-11', null, 'amavasai', '', 'Sources: goldenchennai. Drikpanchang and tamildailycalendar say 10 Sep.'),
  ('2026-10-10', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar, goldenchennai.'),
  ('2026-11-08', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar. Goldenchennai says 9 Nov.'),
  ('2026-11-09', null, 'amavasai', '', 'Sources: goldenchennai. Drikpanchang and tamildailycalendar say 8 Nov.'),
  ('2026-12-08', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar, goldenchennai.'),
  ('2026-12-09', null, 'amavasai', '', 'Sources: goldenchennai. Goldenchennai lists 8 and 9 Dec; the others only 8 Dec.'),
  ('2027-01-07', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-02-06', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-03-07', null, 'amavasai', '', 'Sources: drikpanchang. Drikpanchang lists 7 and 8 Mar; tamildailycalendar only 8 Mar.'),
  ('2027-03-08', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-04-06', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-05-06', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-06-04', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-07-03', null, 'amavasai', '', 'Sources: drikpanchang. Drikpanchang lists 3 and 4 Jul; tamildailycalendar only 4 Jul.'),
  ('2027-07-04', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-08-02', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-08-31', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-09-29', null, 'amavasai', '', 'Sources: drikpanchang. Drikpanchang lists 29 and 30 Sep; tamildailycalendar only 30 Sep.'),
  ('2027-09-30', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-10-29', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-11-27', null, 'amavasai', '', 'Sources: drikpanchang. Drikpanchang lists 27 and 28 Nov; tamildailycalendar only 28 Nov.'),
  ('2027-11-28', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2027-12-27', null, 'amavasai', '', 'Sources: drikpanchang, tamildailycalendar.'),
  ('2026-01-27', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-02-23', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-02-24', null, 'kiruthigai', '', 'Sources: tamildot. Tamildot lists 23 and 24 Feb; drikpanchang only 23 Feb.'),
  ('2026-03-23', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-04-19', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-05-16', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-06-13', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-07-10', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-08-06', null, 'kiruthigai', '', 'Sources: tamildot. Drikpanchang says 7 Aug.'),
  ('2026-08-07', null, 'kiruthigai', '', 'Sources: drikpanchang. Tamildot says 6 Aug.'),
  ('2026-09-03', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-09-30', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-10-27', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2026-11-24', null, 'kiruthigai', 'Karthigai Deepam', 'Sources: drikpanchang, tamildot.'),
  ('2026-12-21', null, 'kiruthigai', '', 'Sources: drikpanchang, tamildot.'),
  ('2027-01-18', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-02-14', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-03-13', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-04-09', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-05-07', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-06-03', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-07-01', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-07-28', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-08-24', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-09-21', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-10-18', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-11-14', null, 'kiruthigai', '', 'Sources: drikpanchang. Only one source found.'),
  ('2027-12-11', null, 'kiruthigai', 'Karthigai Deepam', 'Sources: drikpanchang. Only one source found.'),
  ('2026-09-18', '2026-10-17', 'puratasi', '', 'Sources: goldenchennai, prokerala.'),
  ('2027-09-17', '2027-10-17', 'puratasi', '', 'Sources: prokerala. Only one source found: Purattasi 1 on 17 Sep, Aippasi 1 on 18 Oct.')
on conflict (date, type) do update set
  end_date = excluded.end_date, label = excluded.label, note = excluded.note;

select private.seed_household_calendar(id) from public.households;
