-- ============================================================================
-- PRABAS Food Planner · 0012 prepared catalogue
--
-- GENERATED by `npm run catalog` from supabase/seed/prepared.psv (and the starter
-- dishes in dish_catalog.psv). Edit those files, not this one.
-- (10 prepared items, 13 dishes that use them.)
--
-- The catalogue gains prep plans and uses; new households get them with their dishes.
-- Every existing household gets the new items. Its starter dishes that now use one
-- (dosa uses batter) change only if they still have their starter ingredients: a dish
-- someone has edited is left as it is.
-- ============================================================================

alter table private.dish_catalog
  add column if not exists prep_plan jsonb,
  -- [{dish: <dish catalogue key>, quantity, optional?, prefers_aged?}]
  add column if not exists uses jsonb not null default '[]';

-- Catalogue ingredients ([{item: key, quantity, optional?}]) as a household's own
-- ([{item_id, quantity, optional?}]). The same mapping as seeding in 0006, so a starter
-- dish nobody has edited compares equal.
create or replace function private.catalog_ingredients(p_household uuid, p_list jsonb) returns jsonb
language sql stable
set search_path = ''
as $$
  select coalesce(jsonb_agg(
           jsonb_build_object('item_id', i.id, 'quantity', (x.v ->> 'quantity')::numeric)
           || case when (x.v ->> 'optional')::boolean then '{"optional": true}'::jsonb else '{}'::jsonb end
           order by x.ord), '[]'::jsonb)
  from jsonb_array_elements(coalesce(p_list, '[]'::jsonb)) with ordinality as x (v, ord)
  join public.items i on i.household_id = p_household and i.catalog_key = x.v ->> 'item'
$$;

-- Catalogue uses ([{dish: key, …}]) as a household's ([{dish_id, …}]).
create or replace function private.catalog_uses(p_household uuid, p_list jsonb) returns jsonb
language sql stable
set search_path = ''
as $$
  select coalesce(jsonb_agg((x.v - 'dish') || jsonb_build_object('dish_id', d.id) order by x.ord), '[]'::jsonb)
  from jsonb_array_elements(coalesce(p_list, '[]'::jsonb)) with ordinality as x (v, ord)
  join public.dishes d on d.household_id = p_household and d.catalog_key = x.v ->> 'dish'
$$;

create or replace function private.catalog_prep_plan(p_household uuid, p_plan jsonb) returns jsonb
language sql stable
set search_path = ''
as $$
  select case when p_plan is null then null
    else p_plan || jsonb_build_object('ingredients', private.catalog_ingredients(p_household, p_plan -> 'ingredients')) end
$$;

-- Copies catalogue dishes into a household. Same as 0006, plus prep plans, and what
-- each newly added dish uses (filled in after, like sides, once every dish is there).
create or replace function private.seed_household_dishes(p_household uuid) returns int
language plpgsql
set search_path = ''
as $$
declare
  added uuid[];
begin
  with ins as (
    insert into public.dishes (
      household_id, catalog_key, name_ta, name_en, aliases, type, meals, tags,
      ingredients, is_veg, prep_plan, notes, created_by, updated_by
    )
    select
      p_household, c.key, c.name_ta, c.name_en, c.aliases, c.type, c.meals, c.tags,
      private.catalog_ingredients(p_household, c.ingredients),
      not exists (
        select 1
        from jsonb_array_elements(c.ingredients) x (v)
        join public.items i on i.household_id = p_household and i.catalog_key = x.v ->> 'item'
        where i.category in ('meat', 'fish', 'egg')
      ),
      private.catalog_prep_plan(p_household, c.prep_plan),
      c.notes, null, null
    from private.dish_catalog c
    on conflict (household_id, catalog_key) do nothing
    returning id
  )
  select coalesce(array_agg(id), '{}') into added from ins;

  update public.dishes d
  set side_ids = coalesce((
    select array_agg(s.id order by k.ord)
    from unnest(c.sides) with ordinality as k (key, ord)
    join public.dishes s on s.household_id = p_household and s.catalog_key = k.key and s.id <> d.id
  ), '{}')
  from private.dish_catalog c
  where d.id = any (added) and d.catalog_key = c.key and cardinality(c.sides) > 0;

  update public.dishes d
  set uses_prepared = private.catalog_uses(p_household, c.uses)
  from private.dish_catalog c
  where d.id = any (added) and d.catalog_key = c.key and jsonb_array_length(c.uses) > 0;

  return cardinality(added);
end
$$;

-- ---------------------------------------------------------------------------
-- The catalogue: new prepared items, then the starter dishes that use them.
-- ---------------------------------------------------------------------------

insert into private.dish_catalog (key, name_ta, name_en, aliases, type, meals, tags, ingredients, sides, prep_plan, uses) values
  ('idli_dosa_batter', 'இட்லி தோசை மாவு', 'Idli/dosa batter', array['idli maavu', 'dosa maavu', 'idli batter', 'dosa batter', 'maavu']::text[], 'prepared', array[]::text[], array[]::text[], '[]'::jsonb, array[]::text[], '{"stages":[{"key":"soak","hours":5,"action":true,"takes_ingredients":true},{"key":"grind","hours":0,"action":true},{"key":"ferment","hours":10,"action":false,"adjustable":true}],"yield":4,"unit":"meals","keeps_days":3,"keep_going":true,"ingredients":[{"item":"idli_arisi","quantity":2000},{"item":"ulutham_paruppu","quantity":500},{"item":"vendhayam","quantity":10}]}'::jsonb, '[]'::jsonb),
  ('paruppu_dosa_batter', 'அடை மாவு', 'Paruppu dosa batter', array['adai maavu', 'adai batter', 'paruppu dosa maavu']::text[], 'prepared', array[]::text[], array[]::text[], '[]'::jsonb, array[]::text[], '{"stages":[{"key":"soak","hours":3,"action":true,"takes_ingredients":true},{"key":"grind","hours":0,"action":true}],"yield":2,"unit":"meals","keeps_days":2,"keep_going":false,"ingredients":[{"item":"puzhungal_arisi","quantity":400},{"item":"thuvaram_paruppu","quantity":200},{"item":"kadalai_paruppu","quantity":200},{"item":"ulutham_paruppu","quantity":100},{"item":"pasi_paruppu","quantity":100},{"item":"vara_milagai","quantity":16},{"item":"inji","quantity":30}]}'::jsonb, '[]'::jsonb),
  ('pazhaya_sadam', 'பழைய சாதம்', 'Pazhaya sadam', array['pazhaya sadam', 'pazhaya soru', 'neeragaram', 'fermented rice', 'old rice']::text[], 'variety_rice', array['breakfast']::text[], array['curd']::text[], '[{"item":"mor","quantity":500},{"item":"chinna_vengayam","quantity":75},{"item":"pachai_milagai","quantity":10,"optional":true}]'::jsonb, array[]::text[], '{"stages":[{"key":"soak","hours":10,"action":true,"takes_ingredients":true}],"yield":1,"unit":"meals","keeps_days":1,"keep_going":false,"ingredients":[{"item":"puzhungal_arisi","quantity":400}]}'::jsonb, '[{"dish":"pazhaya_sadam","quantity":1}]'::jsonb),
  ('soaked_chana', 'ஊறவைத்த கொண்டைக்கடலை', 'Soaked chana', array['soaked chana', 'soaked channa', 'kondakadalai']::text[], 'prepared', array[]::text[], array[]::text[], '[]'::jsonb, array[]::text[], '{"stages":[{"key":"soak","hours":8,"action":true,"takes_ingredients":true}],"yield":1,"unit":"meals","keeps_days":2,"keep_going":false,"ingredients":[{"item":"vellai_kondakadalai","quantity":250}]}'::jsonb, '[]'::jsonb),
  ('chapathi_maavu', 'சப்பாத்தி மாவு', 'Chapati dough', array['chapati dough', 'chapathi maavu', 'atta dough']::text[], 'prepared', array[]::text[], array[]::text[], '[]'::jsonb, array[]::text[], '{"stages":[{"key":"knead","hours":0,"action":true,"takes_ingredients":true},{"key":"rest","hours":0.5,"action":false}],"yield":2,"unit":"meals","keeps_days":2,"keep_going":false,"ingredients":[{"item":"godhumai_mavu","quantity":1000},{"item":"kadalai_ennai","quantity":20}]}'::jsonb, '[]'::jsonb),
  ('puliyogare_paste', 'புளிக்காய்ச்சல்', 'Puliyogare paste', array['pulikaichal', 'puli kaichal', 'puliyogare paste', 'puliyodharai paste']::text[], 'prepared', array[]::text[], array[]::text[], '[]'::jsonb, array[]::text[], '{"stages":[{"key":"cook","hours":1,"action":true,"takes_ingredients":true}],"yield":6,"unit":"meals","keeps_days":30,"keep_going":false,"ingredients":[{"item":"puli","quantity":300},{"item":"nallennai","quantity":250},{"item":"kadalai_paruppu","quantity":60},{"item":"vara_milagai","quantity":30},{"item":"vendhayam","quantity":15},{"item":"vellam","quantity":60},{"item":"ellu","quantity":20},{"item":"karuveppilai","quantity":1}]}'::jsonb, '[]'::jsonb),
  ('idli_podi', 'இட்லி பொடி', 'Idli podi', array['idli podi', 'milagai podi', 'gunpowder', 'paruppu podi']::text[], 'chutney', array['breakfast', 'dinner']::text[], array[]::text[], '[{"item":"nallennai","quantity":25}]'::jsonb, array[]::text[], '{"stages":[{"key":"roast","hours":1,"action":true,"takes_ingredients":true}],"yield":10,"unit":"meals","keeps_days":60,"keep_going":false,"ingredients":[{"item":"ulutham_paruppu","quantity":100},{"item":"kadalai_paruppu","quantity":50},{"item":"vara_milagai","quantity":15},{"item":"ellu","quantity":15}]}'::jsonb, '[{"dish":"idli_podi","quantity":1}]'::jsonb),
  ('thakkali_thokku', 'தக்காளித் தொக்கு', 'Tomato thokku', array['thakkali thokku', 'tomato thokku', 'tomato pickle']::text[], 'chutney', array['breakfast', 'dinner']::text[], array[]::text[], '[]'::jsonb, array[]::text[], '{"stages":[{"key":"cook","hours":1,"action":true,"takes_ingredients":true}],"yield":6,"unit":"meals","keeps_days":14,"keep_going":false,"ingredients":[{"item":"thakkali","quantity":1000},{"item":"nallennai","quantity":150},{"item":"milagai_thool","quantity":25},{"item":"vendhayam","quantity":5},{"item":"poondu","quantity":30}]}'::jsonb, '[{"dish":"thakkali_thokku","quantity":1}]'::jsonb)
on conflict (key) do update set
  name_ta = excluded.name_ta, name_en = excluded.name_en, aliases = excluded.aliases,
  type = excluded.type, meals = excluded.meals, tags = excluded.tags,
  ingredients = excluded.ingredients, sides = excluded.sides,
  prep_plan = excluded.prep_plan, uses = excluded.uses;

update private.dish_catalog set
  ingredients = '[]'::jsonb,
  uses = '[{"dish":"idli_dosa_batter","quantity":1}]'::jsonb,
  sides = array['sambar_tiffin', 'thengai_chutney', 'thakkali_chutney', 'idli_podi']::text[]
where key = 'idli';

update private.dish_catalog set
  ingredients = '[{"item":"kadalai_ennai","quantity":100}]'::jsonb,
  uses = '[{"dish":"idli_dosa_batter","quantity":1}]'::jsonb,
  sides = array['sambar_tiffin', 'thengai_chutney', 'kara_chutney', 'idli_podi', 'thakkali_thokku']::text[]
where key = 'dosai';

update private.dish_catalog set
  ingredients = '[{"item":"periya_vengayam","quantity":150},{"item":"thakkali","quantity":150},{"item":"pachai_milagai","quantity":15},{"item":"kadalai_ennai","quantity":100}]'::jsonb,
  uses = '[{"dish":"idli_dosa_batter","quantity":1,"prefers_aged":true}]'::jsonb,
  sides = array['sambar_tiffin', 'thengai_chutney']::text[]
where key = 'uthappam';

update private.dish_catalog set
  ingredients = '[{"item":"chinna_vengayam","quantity":100},{"item":"pachai_milagai","quantity":15},{"item":"kadalai_ennai","quantity":80}]'::jsonb,
  uses = '[{"dish":"idli_dosa_batter","quantity":1,"prefers_aged":true}]'::jsonb,
  sides = array['thengai_chutney', 'kara_chutney']::text[]
where key = 'kuzhi_paniyaram';

update private.dish_catalog set
  ingredients = '[{"item":"chinna_vengayam","quantity":100},{"item":"kadalai_ennai","quantity":100},{"item":"karuveppilai","quantity":0.25}]'::jsonb,
  uses = '[{"dish":"paruppu_dosa_batter","quantity":1}]'::jsonb,
  sides = array['avial', 'thengai_chutney']::text[]
where key = 'adai';

update private.dish_catalog set
  ingredients = '[{"item":"mor","quantity":1000},{"item":"chinna_vengayam","quantity":75,"optional":true}]'::jsonb,
  uses = '[{"dish":"ragi_koozh","quantity":5}]'::jsonb,
  sides = array[]::text[],
  prep_plan = '{"stages":[{"key":"soak","hours":9,"action":true,"takes_ingredients":true},{"key":"cook","hours":1,"action":true},{"key":"ferment","hours":24,"action":false,"adjustable":true}],"yield":10,"unit":"glasses","keeps_days":3,"keep_going":false,"ingredients":[{"item":"ragi_mavu","quantity":400},{"item":"puzhungal_arisi","quantity":100}]}'::jsonb
where key = 'ragi_koozh';

update private.dish_catalog set
  ingredients = '[{"item":"mor","quantity":1000},{"item":"chinna_vengayam","quantity":75,"optional":true}]'::jsonb,
  uses = '[{"dish":"kambu_koozh","quantity":5}]'::jsonb,
  sides = array[]::text[],
  prep_plan = '{"stages":[{"key":"soak","hours":8,"action":true,"takes_ingredients":true},{"key":"cook","hours":1,"action":true},{"key":"ferment","hours":12,"action":false,"adjustable":true}],"yield":10,"unit":"glasses","keeps_days":2,"keep_going":false,"ingredients":[{"item":"kambu","quantity":500}]}'::jsonb
where key = 'kambu_koozh';

update private.dish_catalog set
  ingredients = '[{"item":"kadalai_ennai","quantity":40}]'::jsonb,
  uses = '[{"dish":"chapathi_maavu","quantity":1}]'::jsonb,
  sides = array['veg_kurma', 'chana_masala', 'paruppu_kadaiyal', 'thakkali_thokku']::text[]
where key = 'chapathi';

update private.dish_catalog set
  ingredients = '[{"item":"pacharisi","quantity":400},{"item":"verkadalai","quantity":50},{"item":"nallennai","quantity":30}]'::jsonb,
  uses = '[{"dish":"puliyogare_paste","quantity":1}]'::jsonb,
  sides = array['urulai_roast', 'vazhakkai_varuval']::text[]
where key = 'puli_sadam';

update private.dish_catalog set
  ingredients = '[{"item":"periya_vengayam","quantity":200},{"item":"thakkali","quantity":250},{"item":"inji","quantity":15},{"item":"poondu","quantity":15},{"item":"garam_masala","quantity":10},{"item":"kadalai_ennai","quantity":40}]'::jsonb,
  uses = '[{"dish":"soaked_chana","quantity":1}]'::jsonb,
  sides = array[]::text[]
where key = 'chana_masala';

-- ---------------------------------------------------------------------------
-- Households that exist: the new items, then their starter dishes.
-- ---------------------------------------------------------------------------

select private.seed_household_dishes(id) from public.households;

-- Idli
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"idli_dosa_batter","quantity":1}]'::jsonb)
where d.catalog_key = 'idli'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"idli_arisi","quantity":500},{"item":"ulutham_paruppu","quantity":125}]'::jsonb);
update public.dishes d set side_ids = d.side_ids || array(
  select s.id from unnest(array['idli_podi']::text[]) with ordinality as k (key, ord)
  join public.dishes s on s.household_id = d.household_id and s.catalog_key = k.key
  where not s.id = any (d.side_ids) and s.id <> d.id
  order by k.ord)
where d.catalog_key = 'idli' and cardinality(d.side_ids) < 9;

-- Dosa
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[{"item":"kadalai_ennai","quantity":100}]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"idli_dosa_batter","quantity":1}]'::jsonb)
where d.catalog_key = 'dosai'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"idli_arisi","quantity":500},{"item":"ulutham_paruppu","quantity":125},{"item":"kadalai_ennai","quantity":100}]'::jsonb);
update public.dishes d set side_ids = d.side_ids || array(
  select s.id from unnest(array['idli_podi', 'thakkali_thokku']::text[]) with ordinality as k (key, ord)
  join public.dishes s on s.household_id = d.household_id and s.catalog_key = k.key
  where not s.id = any (d.side_ids) and s.id <> d.id
  order by k.ord)
where d.catalog_key = 'dosai' and cardinality(d.side_ids) < 9;

-- Uthappam
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[{"item":"periya_vengayam","quantity":150},{"item":"thakkali","quantity":150},{"item":"pachai_milagai","quantity":15},{"item":"kadalai_ennai","quantity":100}]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"idli_dosa_batter","quantity":1,"prefers_aged":true}]'::jsonb)
where d.catalog_key = 'uthappam'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"idli_arisi","quantity":500},{"item":"ulutham_paruppu","quantity":125},{"item":"periya_vengayam","quantity":150},{"item":"thakkali","quantity":150},{"item":"pachai_milagai","quantity":15},{"item":"kadalai_ennai","quantity":100}]'::jsonb);

-- Kuzhi paniyaram
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[{"item":"chinna_vengayam","quantity":100},{"item":"pachai_milagai","quantity":15},{"item":"kadalai_ennai","quantity":80}]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"idli_dosa_batter","quantity":1,"prefers_aged":true}]'::jsonb)
where d.catalog_key = 'kuzhi_paniyaram'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"idli_arisi","quantity":400},{"item":"ulutham_paruppu","quantity":100},{"item":"chinna_vengayam","quantity":100},{"item":"pachai_milagai","quantity":15},{"item":"kadalai_ennai","quantity":80}]'::jsonb);

-- Adai
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[{"item":"chinna_vengayam","quantity":100},{"item":"kadalai_ennai","quantity":100},{"item":"karuveppilai","quantity":0.25}]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"paruppu_dosa_batter","quantity":1}]'::jsonb)
where d.catalog_key = 'adai'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"puzhungal_arisi","quantity":200},{"item":"thuvaram_paruppu","quantity":100},{"item":"kadalai_paruppu","quantity":100},{"item":"ulutham_paruppu","quantity":50},{"item":"pasi_paruppu","quantity":50},{"item":"vara_milagai","quantity":8},{"item":"chinna_vengayam","quantity":100},{"item":"inji","quantity":15},{"item":"kadalai_ennai","quantity":100},{"item":"karuveppilai","quantity":0.25}]'::jsonb);

-- Ragi koozh
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[{"item":"mor","quantity":1000},{"item":"chinna_vengayam","quantity":75,"optional":true}]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"ragi_koozh","quantity":5}]'::jsonb),
  prep_plan = coalesce(d.prep_plan, private.catalog_prep_plan(d.household_id, '{"stages":[{"key":"soak","hours":9,"action":true,"takes_ingredients":true},{"key":"cook","hours":1,"action":true},{"key":"ferment","hours":24,"action":false,"adjustable":true}],"yield":10,"unit":"glasses","keeps_days":3,"keep_going":false,"ingredients":[{"item":"ragi_mavu","quantity":400},{"item":"puzhungal_arisi","quantity":100}]}'::jsonb))
where d.catalog_key = 'ragi_koozh'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"ragi_mavu","quantity":200},{"item":"puzhungal_arisi","quantity":50},{"item":"mor","quantity":1000},{"item":"chinna_vengayam","quantity":75,"optional":true}]'::jsonb);

-- Kambu koozh
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[{"item":"mor","quantity":1000},{"item":"chinna_vengayam","quantity":75,"optional":true}]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"kambu_koozh","quantity":5}]'::jsonb),
  prep_plan = coalesce(d.prep_plan, private.catalog_prep_plan(d.household_id, '{"stages":[{"key":"soak","hours":8,"action":true,"takes_ingredients":true},{"key":"cook","hours":1,"action":true},{"key":"ferment","hours":12,"action":false,"adjustable":true}],"yield":10,"unit":"glasses","keeps_days":2,"keep_going":false,"ingredients":[{"item":"kambu","quantity":500}]}'::jsonb))
where d.catalog_key = 'kambu_koozh'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"kambu","quantity":250},{"item":"mor","quantity":1000},{"item":"chinna_vengayam","quantity":75,"optional":true}]'::jsonb);

-- Chapati
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[{"item":"kadalai_ennai","quantity":40}]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"chapathi_maavu","quantity":1}]'::jsonb)
where d.catalog_key = 'chapathi'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"godhumai_mavu","quantity":500},{"item":"kadalai_ennai","quantity":50}]'::jsonb);
update public.dishes d set side_ids = d.side_ids || array(
  select s.id from unnest(array['thakkali_thokku']::text[]) with ordinality as k (key, ord)
  join public.dishes s on s.household_id = d.household_id and s.catalog_key = k.key
  where not s.id = any (d.side_ids) and s.id <> d.id
  order by k.ord)
where d.catalog_key = 'chapathi' and cardinality(d.side_ids) < 9;

-- Tamarind rice
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[{"item":"pacharisi","quantity":400},{"item":"verkadalai","quantity":50},{"item":"nallennai","quantity":30}]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"puliyogare_paste","quantity":1}]'::jsonb)
where d.catalog_key = 'puli_sadam'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"pacharisi","quantity":400},{"item":"puli","quantity":75},{"item":"nallennai","quantity":100},{"item":"verkadalai","quantity":50},{"item":"kadalai_paruppu","quantity":20},{"item":"vara_milagai","quantity":8},{"item":"vendhayam","quantity":5},{"item":"vellam","quantity":15},{"item":"karuveppilai","quantity":0.25}]'::jsonb);

-- Chana masala
update public.dishes d set
  ingredients = private.catalog_ingredients(d.household_id, '[{"item":"periya_vengayam","quantity":200},{"item":"thakkali","quantity":250},{"item":"inji","quantity":15},{"item":"poondu","quantity":15},{"item":"garam_masala","quantity":10},{"item":"kadalai_ennai","quantity":40}]'::jsonb),
  uses_prepared = private.catalog_uses(d.household_id, '[{"dish":"soaked_chana","quantity":1}]'::jsonb)
where d.catalog_key = 'chana_masala'
  and d.ingredients = private.catalog_ingredients(d.household_id, '[{"item":"vellai_kondakadalai","quantity":250},{"item":"periya_vengayam","quantity":200},{"item":"thakkali","quantity":250},{"item":"inji","quantity":15},{"item":"poondu","quantity":15},{"item":"garam_masala","quantity":10},{"item":"kadalai_ennai","quantity":40}]'::jsonb);
